// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;
using JetBrains.Annotations;

namespace XMP.Droid.Views
{
    public partial class LoginActivityViewHolder
    {
        [NotNull] private readonly Activity activity;

        [CanBeNull] private EditText loginEdit;
        [CanBeNull] private EditText passwordEdit;
        [CanBeNull] private Button signInButton;
        [CanBeNull] private LinearLayout errorOverlayView;
        [CanBeNull] private TextView errorText;
        [CanBeNull] private ImageView errorOverlayTriangleImage;

        public LoginActivityViewHolder([NotNull] Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        [NotNull]
        public EditText LoginEdit =>
            loginEdit ?? (loginEdit = activity.FindViewById<EditText>(Resource.Id.login_edit));

        [NotNull]
        public EditText PasswordEdit =>
            passwordEdit ?? (passwordEdit = activity.FindViewById<EditText>(Resource.Id.password_edit));

        [NotNull]
        public Button SignInButton =>
            signInButton ?? (signInButton = activity.FindViewById<Button>(Resource.Id.sign_in_button));

        [NotNull]
        public LinearLayout ErrorOverlayView =>
            errorOverlayView ?? (errorOverlayView = activity.FindViewById<LinearLayout>(Resource.Id.error_overlay_view));

        [NotNull]
        public TextView ErrorText =>
            errorText ?? (errorText = activity.FindViewById<TextView>(Resource.Id.error_text));

        [NotNull]
        public ImageView ErrorOverlayTriangleImage =>
            errorOverlayTriangleImage ?? (errorOverlayTriangleImage = activity.FindViewById<ImageView>(Resource.Id.error_overlay_triangle_image));
    }

}
// ReSharper restore All
